# .github/workflows/sonarcloud.yml
name: Análisis SonarCloud

on:
  pull_request:
    branches:
      - dev

jobs:
  sonarQubeAnalysis:
    runs-on: ubuntu-latest

    steps:
      # Paso para clonar el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso para configurar JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # Paso para almacenar en caché las dependencias de SonarCloud
      - name: Cache SonarCloud dependencies
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/*.java') }}
          restore-keys: |
            ${{ runner.os }}-sonar-

      # Paso para ejecutar el análisis de SonarCloud
      - name: Run SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew sonarqube \
            -Dsonar.projectKey=SeekopEnterprise_BI-ADMIN-INTERFACES-PADRE \
            -Dsonar.organization=seekopenterprise \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN

      # Paso para verificar el estado de la Quality Gate de SonarCloud
      - name: SonarCloud Quality Gate
        id: check_quality_gate
        run: |
          status=$(curl -u ${{ secrets.SONAR_TOKEN }}: \
                  "https://sonarcloud.io/api/qualitygates/project_status?projectKey=SeekopEnterprise_BI-ADMIN-INTERFACES-PADRE" \
                  | jq -r '.projectStatus.status')
          echo "El estado de la Quality Gate es $status"
          echo "::set-output name=status::$status"

      # Paso para comentar en el pull request si la Quality Gate falla
      - name: Comment on Pull Request
        if: ${{ steps.check_quality_gate.outputs.status != 'OK' }}
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            :x: ¡La Quality Gate de SonarCloud falló!
            Por favor, revisa el reporte de SonarCloud para más detalles.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
